In [27]:
import pandas as pd
cols = ['engine_id', 'cycle',
        'op1', 'op2', 'op3'] + \
       [f'sensor{i}' for i in range(1,22)]
df = pd.read_csv('../dataset/train_FD001.txt',names=cols,sep=r"\s+")
df.head(5)

,engine_id,cycle,op1,op2,op3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor12,sensor13,sensor14,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [28]:
df.shape
df.tail(10)

,engine_id,cycle,op1,op2,op3,sensor1,sensor2,sensor3,sensor4,sensor5,...,sensor12,sensor13,sensor14,sensor15,sensor16,sensor17,sensor18,sensor19,sensor20,sensor21
20621,100,191,-0.0005,-0.0000,100.0,518.67,643.69,1610.87,1427.19,14.62,...,519.80,2388.28,8143.56,8.5092,0.03,398,2388,100.0,38.39,23.1218
20622,100,192,-0.0009,0.0001,100.0,518.67,643.53,1601.23,1419.48,14.62,...,520.59,2388.21,8143.46,8.4892,0.03,397,2388,100.0,38.56,23.0770
20623,100,193,-0.0001,0.0002,100.0,518.67,643.09,1599.81,1428.93,14.62,...,520.11,2388.19,8142.02,8.5424,0.03,397,2388,100.0,38.47,23.0230
20624,100,194,-0.0011,0.0003,100.0,518.67,643.72,1597.29,1427.41,14.62,...,519.55,2388.22,8139.67,8.5215,0.03,394,2388,100.0,38.38,23.1324
20625,100,195,-0.0002,-0.0001,100.0,518.67,643.41,1600.04,1431.90,14.62,...,519.71,2388.28,8142.90,8.5519,0.03,394,2388,100.0,38.14,23.1923
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,...,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,...,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,...,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,...,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,...,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522

In [30]:
data = {
    "engine_id": [1, 1, 1],
    "cycle": [1, 2, 3],
    "sensor1": [500, 505, 510]
}
df_demo = pd.DataFrame(data)
df_demo

   engine_id  cycle  sensor1
0          1      1      500
1          1      2      505
2          1      3      510

In [29]:
data = pd.DataFrame([[30, 21]], columns=['Apples', 'Bananas'])

df_demo = pd.DataFrame(data)
df_demo

   Apples  Bananas
0      30       21

In [ ]:
data = pd.Series(['4 cups','1 cup','2 large','1 can'], index = ['Flour','Milk','Eggs','Spam'], name='Dinner')

df_demo = pd.DataFrame(data)
df_demo

        Dinner
Flour   4 cups
Milk     1 cup
Eggs   2 large
Spam     1 can